#!/bin/bash
#awk '/\/\/\s*@WCA\s*loop\s*=\s*([0-9]+)/ {print NR}' $@
LINENUM=()
VALUE=()

FILENAME=$(basename $@)

sed -n '/.*\(\/\/\s*@WCA\s*loop\s*=\s*\([0-9]\+\)\)$/=' $@ > $FILENAME.line
sed -n 's/.*\(\/\/\s*@WCA\s*loop\s*=\s*\([0-9]\+\)\)$/\2/p' $@ > $FILENAME.value

paste -d',' $FILENAME.line $FILENAME.value > $FILENAME.wca
rm $FILENAME.line $FILENAME.value

