#!/bin/bash
#awk '/\/\/\s*@WCA\s*loop\s*=\s*([0-9]+)/ {print NR}' $@
LINENUM=()
VALUE=()

FILENAME=$(basename $@)

LINENUM=($(sed -n '/.*\(\/\/\s*@WCA\s*loop\s*=\s*\([0-9]\+\)\s*\)$/=' $@))
VALUE=($(sed -n 's/.*\(\/\/\s*@WCA\s*loop\s*=\s*\([0-9]\+\)\s*\)$/\2/p' $@))

rm -rf $FILENAME.wca
for (( i=0;i<${#LINENUM[@]};i++ ));
do
	printf "${LINENUM[i]},${VALUE[i]}\n" >> $FILENAME.wca
done

#paste -d',' $FILENAME.line $FILENAME.value > $FILENAME.wca
#rm $FILENAME.line $FILENAME.value

